### ISSUE TITLE
Treeview Icons

### ISSUE THREAD

**Issue by andrew-starosciak** [emxxjnm/nvim#1]
I had found your nvim library from a screenshot on catpuccini. And have been using them so far. They are very well done and i've really been getting the hang of it.

My question was that I am using this in both ubuntu on WSL and a pc, I had installed the Input Font as recommended but most of my icons are diamonds with a question mark (as if they arent available in that font). I've switched to a nerd font and some icons show up but not all of them (for example the folders icon).

What do you suggest would be the best way to get these, or should I fork and change them in the `styles.lua` file.

Thanks again!

**Comment by emxxjnm** [comment]
Hi, @andrew-starosciak 

You can check if your terminal supports nerd fonts and set the font family.
It is recommended to use `kitty` or `Alarcitty`.
