### ISSUE TITLE
how do you set nvim-cmp FloatBorder to transparent?

### ISSUE THREAD

**Issue by CcccX2017** [emxxjnm/nvim#2]
I tried setting Catppuccin custom highlights FloatBorder background to colors.none, but the cmp float is not transparent.
![image](https://github.com/emxxjnm/nvim/assets/33515652/7bb9f80d-2236-4d61-94bf-f6a1e69dc006)

**Comment by emxxjnm** [comment]
> I tried setting Catppuccin custom highlights FloatBorder background to colors.none, but the cmp float is not transparent. ![image](https://private-user-images.githubusercontent.com/33515652/345989252-7bb9f80d-2236-4d61-94bf-f6a1e69dc006.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTg0MzUsIm5iZiI6MTcyMDE1ODEzNSwicGF0aCI6Ii8zMzUxNTY1Mi8zNDU5ODkyNTItN2JiOWY4MGQtMjIzNi00ZDYxLTk0YmYtZjZhMWU2OWRjMDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA1NDIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNmVjNzIyMzViMTUwYWQ5MGFjYTlhMGU3MzMxNzM2MjJjMmJkMjZlNmNlMzE0YTUxMzc5ZGIzMjI3ZDk3NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bvM1uykOeFNGpMQbZbg5F9ZO_zenLcfYQlzvWF8jmQ4)


@CcccX2017 看看你这个 winblend 这个配置是不是不是 0， [Catppuccin](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/editor.lua#L41) 根据这个来判断的
这里有说明 https://neovim.io/doc/user/options.html#'winblend

**Comment by CcccX2017** [comment]
> > 我尝试将 Catppuccin 自定义高亮 FloatBorder 背景设置为 colors.none，但 cmp 浮点不透明。![图像](https://private-user-images.githubusercontent.com/33515652/345989252-7bb9f80d-2236-4d61-94bf-f6a1e69dc006.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTg0MzUsIm5iZiI6MTcyMDE1ODEzNSwicGF0aCI6Ii8zMzUxNTY1Mi8zNDU5ODkyNTItN2JiOWY4MGQtMjIzNi00ZDYxLTk0YmYtZjZhMWU2OWRjMDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA1NDIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNmVjNzIyMzViMTUwYWQ5MGFjYTlhMGU3MzMxNzM2MjJjMmJkMjZlNmNlMzE0YTUxMzc5ZGIzMjI3ZDk3NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bvM1uykOeFNGpMQbZbg5F9ZO_zenLcfYQlzvWF8jmQ4)
> 
> @CcccX2017看看你这个 winblend 这个配置是不是 0，[Catppuccin](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/editor.lua#L41)根据这个来判断的 这里有说明https://neovim.io/doc/user/options.html#'winblend

感谢，设置好之后确实正常了，但是还有一个问题不知道咋回事，我尝试用你的配置进行分屏或者打开关闭neotree都不会有黑色背景闪一下，用我自己的就会闪一下黑色再变成透明，是不是还有什么需要设置的？

https://github.com/emxxjnm/nvim/assets/33515652/1dda2b8f-de7f-4ed2-a508-163642f50cec
